version: '3.8'

services:
  pacmaze_frontend:
    restart: unless-stopped
    build:
      context: ./frontend
    ports:
      - "8080:3000"
    depends_on:
      - pacmaze_backend

  pacmaze_backend:
    restart: unless-stopped
    build:
      context: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./pacmaze_db:/app/data
